title: "Bahman Seifi's Website"
logo: /assets/img/logo.png
description: "Biophysics, Computational Modeling, and Teaching"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
url: "https://yourusername.github.io"

